export const CREATE_SELLER_START = 'CREATE_SELLER_START';
export const CREATE_SELLER_SUCCESS = 'CREATE_SELLER_SUCCESS';
export const CREATE_SELLER_ERROR = 'CREATE_SELLER_ERROR';


export const VERIFY_SELLER_START = 'VERIFY_SELLER_START';
export const VERIFY_SELLER_SUCCESS = 'VERIFY_SELLER_SUCCESS';
export const VERIFY_SELLER_ERROR = 'VERIFY_SELLER_ERROR';
