//seller
export const CREATE_SELLER_START = "CREATE_SELLER_START";
export const CREATE_SELLER_SUCCESS = "CREATE_SELLER_SUCCESS";
export const CREATE_SELLER_ERROR = "CREATE_SELLER_ERROR";

export const VERIFY_SELLER_START = "VERIFY_SELLER_START";
export const VERIFY_SELLER_SUCCESS = "VERIFY_SELLER_SUCCESS";
export const VERIFY_SELLER_ERROR = "VERIFY_SELLER_ERROR";

export const LOGIN_SELLER_START = "LOGIN_SELLER_START";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_ERROR = "LOGIN_SELLER_ERROR";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const EDIT_SELLER_START = "EDIT_SELLER_START";
export const EDIT_SELLER_SUCCESS = "EDIT_SELLER_SUCCESS";
export const EDIT_SELLER_ERROR = "EDIT_SELLER_ERROR";

//product
export const ADD_PRODUCT_START = "ADD_PRODUCT_START";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR";

export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";

// order status updation
export const UPDATE_ORDER_STATUS_START = "UPDATE_ORDER_STATUS_START";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_ERROR = "UPDATE_ORDER_STATUS_ERROR";
